name: wallet-nile-cron
services:
  wallet-nile-cron:
    container_name: wallet-nile-cron
    build:
      context: ./php
      dockerfile: Dockerfile
    networks:
      - evalink
    environment:
      - PHP_IDE_CONFIG=serverName=LOCAL_PHP_DEFAULT
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ../:/var/app/current
    extra_hosts:
      - "server.wallet.xdev:172.17.0.1" # Replace 172.17.0.1 with the IP you found
      - "secure.wallet-nile-cron.xdev:172.17.0.1"
      - "secure.wallet-nile.xdev:172.17.0.1"
    working_dir: /var/app/current
    ports:
      - "9501:9501" # server port
      - "2112:2112" # metrics port
#    command: tail -f > /dev/null # Keep the container running
    command: sh startup.sh
networks:
  evalink:
    name: evalink
    driver: bridge
  shared-network:
    external: true
