name: wallet-nile-cron
services:
  wallet-nile-cron:
    container_name: wallet-nile-cron
    build:
      context: ./php
      dockerfile: Dockerfile
    networks:
      - evalink
    environment:
      - PHP_IDE_CONFIG=serverName=LOCAL_PHP_DEFAULT
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ../:/var/app/current
    extra_hosts:
      - "server.wallet.xdev:172.17.0.1" # Replace 172.17.0.1 with the IP you found
    working_dir: /var/app/current
    command: sh startup.sh
    ports:
      - "9501:9501" # Swoole default port
      - "2112:2112" # Metrics port

networks:
  evalink:
    name: evalink
    driver: bridge
  shared-network:
    external: true
