name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Deploy via SSM Run Command
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids i-0f995676e4a497cd9 \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["/opt/deployment/git-deploy.sh ${{ github.repository }} ${{ github.sha }}"]' \
          --query 'Command.CommandId' \
          --output text)
        
        echo "SSM Command ID: $COMMAND_ID"
        echo "Deploying commit: ${{ github.sha }}"
        
        # Wait for command completion
        while true; do
          STATUS=$(aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id i-0f995676e4a497cd9 \
            --query 'Status' \
            --output text 2>/dev/null || echo "InProgress")
          
          echo "Deployment status: $STATUS"
          
          if [ "$STATUS" = "Success" ]; then
            echo "Deployment completed successfully"
            
            # Get command output
            aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id i-0f995676e4a497cd9 \
              --query 'StandardOutputContent' \
              --output text
            break
          elif [ "$STATUS" = "Failed" ]; then
            echo "Deployment failed"
            aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id i-0f995676e4a497cd9 \
              --query 'StandardErrorContent' \
              --output text
            exit 1
          elif [ "$STATUS" = "TimedOut" ]; then
            echo "Deployment timed out"
            exit 1
          fi
          
          sleep 10
        done