name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop services
          sudo systemctl stop wallet-nile-cron || true
          sudo systemctl stop nginx || true
          sudo systemctl stop php8.3-fpm || true
          
          # Create app directory if it doesn't exist and clone repo
          if [ ! -d "/var/www/html" ]; then
            sudo git clone https://github.com/yourusername/wallet-nile-cron.git /var/www/html
          else
            cd /var/www/html
            sudo git fetch origin
            sudo git reset --hard origin/main
            sudo git pull origin main
          fi
          
          # Set permissions
          sudo chown -R www-data:www-data /var/www/html
          
          # Install Composer dependencies
          cd /var/www/html
          sudo -u www-data composer install --no-dev --optimize-autoloader
          
          # Create required directories
          sudo mkdir -p /var/www/html/storage/logs
          sudo mkdir -p /var/www/html/storage/cache
          sudo chown -R www-data:www-data /var/www/html/storage
          
          # Configure nginx
          sudo tee /etc/nginx/sites-available/wallet-nile-cron > /dev/null <<EOF
          server {
              listen 80;
              server_name _;
              root /var/www/html/server;
              index index.php;

              location / {
                  try_files \$uri \$uri/ /index.php?\$query_string;
              }

              location ~ \.php$ {
                  fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                  fastcgi_index index.php;
                  include fastcgi_params;
                  fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
          EOF
          
          # Enable nginx site
          sudo ln -sf /etc/nginx/sites-available/wallet-nile-cron /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          
          # Test nginx configuration
          sudo nginx -t
          
          # Install/update systemd service
          sudo cp /var/www/html/systemd/cron.service /etc/systemd/system/wallet-nile-cron.service
          sudo systemctl daemon-reload
          sudo systemctl enable wallet-nile-cron
          sudo systemctl enable nginx
          sudo systemctl enable php8.3-fpm
          
          # Start services
          sudo systemctl start php8.3-fpm
          sudo systemctl start nginx
          sudo systemctl start wallet-nile-cron
          
          # Check service status
          sudo systemctl status php8.3-fpm
          sudo systemctl status nginx
          sudo systemctl status wallet-nile-cron